production:
  sessions:
    default:
      database: unturned_mods_production
      hosts:
        - localhost:27017

development:
  sessions:
    default:
      database: unturned_mods_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: unturned_mods_test
      hosts:
        - localhost:27017

staging:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>